# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

# Use Solid Software's recommended lints
include: package:solid_lints/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    # You can override or add custom rules here if needed.
    # Example:
    # avoid_print: false
    # prefer_single_quotes: true

