name: solid_hello
description: "Hello There App"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  solid_lints: ^0.3.1

flutter:
  uses-material-design: true

  fonts:
    - family: SourGummy
      fonts:
        - asset: assets/fonts/SourGummy_Expanded-Light.ttf
          weight: 300
        - asset: assets/fonts/SourGummy_Expanded-Medium.ttf
          weight: 500

    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf
          weight: 300
